global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081','localhost:8082','localhost:8083'] # we'll run services on 8081.. by default (update later if needed)

  - job_name: 'zipkin'
    static_configs:
      - targets: ['zipkin:9411']