server:
  port: 8084

spring:
  application:
    name: payment-service
  jackson:
    time-zone: Asia/Kolkata

  datasource:
    url: jdbc:postgresql://localhost:5432/eshopdb
    username: postgres
    password: eshop123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC

  kafka:
    bootstrap-servers: localhost:29092

    listener:
      ack-mode: record  # process record by record

    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      enable-auto-commit: false

      # Use ErrorHandlingDeserializer so your DefaultErrorHandler can handle deserialization errors
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      # Tell the ErrorHandlingDeserializer which underlying deserializers to delegate to
      properties:
        # Kafka-level polling stability
        max.poll.interval.ms: 300000        # 5 minutes
        max.poll.records: 50                # Process 50 messages per poll
        fetch.min.bytes: 1
        heartbeat.interval.ms: 3000

        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer

        # Important: don't rely on producer type headers; always deserialize into local type
        spring.json:
          use.type.headers: false
          value:
            default:
              type: com.eshop.payment_service.event.incoming.OrderReservedEvent
          trusted:
            packages: "com.eshop.*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 5

      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        linger.ms: 5
        batch.size: 32768
#        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1